CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX auth_group_permissions_group_id_permission_id_0cd325b0_uniq ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX auth_user_groups_user_id_group_id_94350c0c_uniq ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX auth_user_user_permissions_user_id_permission_id_14a6b632_uniq ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX django_content_type_app_label_model_76bd3d3b_uniq ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX auth_permission_content_type_id_codename_01ab375a_uniq ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "last_name" varchar(150) NOT NULL);
CREATE TABLE IF NOT EXISTS "recipes_ingredientfamily" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL);
CREATE TABLE IF NOT EXISTS "recipes_ingredientphoto" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "path" text NOT NULL, "created_at" datetime NOT NULL, "ingredient_id" integer NOT NULL UNIQUE REFERENCES "recipes_ingredient" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "recipes_ingredientunitmeasure" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL, "label" varchar(50) NOT NULL);
CREATE TABLE IF NOT EXISTS "recipes_notification" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "comment_id" integer NOT NULL REFERENCES "recipes_comment" ("id") DEFERRABLE INITIALLY DEFERRED, "mark_id" integer NOT NULL REFERENCES "recipes_mark" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "recipes_profile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "avatar" text NOT NULL, "date_of_birth" date NOT NULL, "country" varchar(255) NOT NULL, "country_flag" text NOT NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "recipes_recipeingredient" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "quantity" real NOT NULL, "ingredient_id" integer NOT NULL REFERENCES "recipes_ingredient" ("id") DEFERRABLE INITIALLY DEFERRED, "recipe_id" integer NOT NULL REFERENCES "recipes_recipe" ("id") DEFERRABLE INITIALLY DEFERRED, "unit_measure_id" integer NOT NULL REFERENCES "recipes_ingredientunitmeasure" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "recipes_recipemediatype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "label" varchar(255) NOT NULL);
CREATE TABLE IF NOT EXISTS "recipes_recipetype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "label" varchar(255) NOT NULL);
CREATE INDEX "recipes_notification_comment_id_de06543b" ON "recipes_notification" ("comment_id");
CREATE INDEX "recipes_notification_mark_id_0c0360dd" ON "recipes_notification" ("mark_id");
CREATE INDEX "recipes_notification_user_id_6635f122" ON "recipes_notification" ("user_id");
CREATE INDEX "recipes_recipeingredient_ingredient_id_0efc0df1" ON "recipes_recipeingredient" ("ingredient_id");
CREATE INDEX "recipes_recipeingredient_recipe_id_76423229" ON "recipes_recipeingredient" ("recipe_id");
CREATE INDEX "recipes_recipeingredient_unit_measure_id_e750f68c" ON "recipes_recipeingredient" ("unit_measure_id");
CREATE TABLE IF NOT EXISTS "recipes_recipemedia" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "media_type_id" integer NOT NULL REFERENCES "recipes_recipemediatype" ("id") DEFERRABLE INITIALLY DEFERRED, "recipe_id" integer NOT NULL REFERENCES "recipes_recipe" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "recipes_recipemedia_media_type_id_6579ffd9" ON "recipes_recipemedia" ("media_type_id");
CREATE INDEX "recipes_recipemedia_recipe_id_b4c459ba" ON "recipes_recipemedia" ("recipe_id");
CREATE TABLE IF NOT EXISTS "recipes_recipe" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "description" text NOT NULL, "realization_cost" real NOT NULL, "preparation_time" bigint NOT NULL, "cooking_time" bigint NOT NULL, "relaxation_time" bigint NOT NULL, "mean_of_marks" real NOT NULL, "number_of_marks" integer NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "recipe_difficulty_id" integer NOT NULL REFERENCES "recipes_recipedifficulty" ("id") DEFERRABLE INITIALLY DEFERRED, "recipe_type_id" integer NOT NULL REFERENCES "recipes_recipetype" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "recipes_recipe_recipe_difficulty_id_4ad638ca" ON "recipes_recipe" ("recipe_difficulty_id");
CREATE INDEX "recipes_recipe_recipe_type_id_9911e40c" ON "recipes_recipe" ("recipe_type_id");
CREATE INDEX "recipes_recipe_user_id_c14b3239" ON "recipes_recipe" ("user_id");
CREATE TABLE IF NOT EXISTS "recipes_mark" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "mark_score" real NOT NULL, "created_at" datetime NOT NULL, "recipe_id" integer NOT NULL REFERENCES "recipes_recipe" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "recipes_mark_recipe_id_3de08405" ON "recipes_mark" ("recipe_id");
CREATE INDEX "recipes_mark_user_id_60699743" ON "recipes_mark" ("user_id");
CREATE TABLE IF NOT EXISTS "recipes_ingredient" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "family_id" integer NOT NULL REFERENCES "recipes_ingredientfamily" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "recipes_ingredient_family_id_e305a48e" ON "recipes_ingredient" ("family_id");
CREATE TABLE IF NOT EXISTS "recipes_ingredient_unit_measure" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "ingredient_id" integer NOT NULL REFERENCES "recipes_ingredient" ("id") DEFERRABLE INITIALLY DEFERRED, "ingredientunitmeasure_id" integer NOT NULL REFERENCES "recipes_ingredientunitmeasure" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX recipes_ingredient_unit_measure_ingredient_id_ingredientunitmeasure_id_9f9f13aa_uniq ON "recipes_ingredient_unit_measure" ("ingredient_id", "ingredientunitmeasure_id");
CREATE INDEX "recipes_ingredient_unit_measure_ingredient_id_0d8f3fed" ON "recipes_ingredient_unit_measure" ("ingredient_id");
CREATE INDEX "recipes_ingredient_unit_measure_ingredientunitmeasure_id_7f115c67" ON "recipes_ingredient_unit_measure" ("ingredientunitmeasure_id");
CREATE TABLE IF NOT EXISTS "recipes_comment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "recipe_id" integer NOT NULL REFERENCES "recipes_recipe" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "recipes_comment_recipe_id_251ae78a" ON "recipes_comment" ("recipe_id");
CREATE INDEX "recipes_comment_user_id_a283f2b7" ON "recipes_comment" ("user_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "recipes_recipedifficulty" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "label" varchar(255) NOT NULL, "level" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "recipes_recipestep" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "description" text NOT NULL, "recipe_id" integer NOT NULL REFERENCES "recipes_recipe" ("id") DEFERRABLE INITIALLY DEFERRED, "level" integer NOT NULL);
CREATE INDEX "recipes_recipestep_recipe_id_f5329783" ON "recipes_recipestep" ("recipe_id");
