# Generated by Django 2.0.4 on 2018-06-24 09:51

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientphoto',
            name='path',
            field=models.ImageField(upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=recipes.models.avatar_path),
        ),
    ]
