# Generated by Django 2.0.4 on 2018-06-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180624_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientphoto',
            name='path',
            field=models.ImageField(upload_to='static/media/ingredients/'),
        ),
    ]
