# Generated by Django 2.0.4 on 2018-06-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180617_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipemedia',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='relaxation_time',
            field=models.TimeField(default=0),
        ),
    ]
