# Generated by Django 2.0.4 on 2018-07-04 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180704_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientphoto',
            name='path',
            field=models.ImageField(upload_to='ingredients/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/avatars/default_avatar.png', upload_to=recipes.models.avatar_path),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
