# Generated by Django 2.0.4 on 2018-06-18 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20180618_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='relaxation_time',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='recipemedia',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='recipes.Recipe'),
        ),
    ]
