# Generated by Django 2.0.4 on 2018-06-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_recipe_number_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='mean_of_marks',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='number_of_marks',
        ),
    ]
