# Generated by Django 2.0.4 on 2018-06-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_imagerecipe_videorecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemedia',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='recipemedia',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='imagerecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='videorecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='recipes.Recipe'),
        ),
        migrations.DeleteModel(
            name='RecipeMedia',
        ),
        migrations.DeleteModel(
            name='RecipeMediaType',
        ),
    ]
