# Generated by Django 2.0.4 on 2018-06-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20180628_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_types',
            field=models.ManyToManyField(related_name='types', to='recipes.RecipeType'),
        ),
    ]
