# Generated by Django 2.0.4 on 2018-06-19 20:07

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20180619_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to=recipes.models.user_directory_path),
        ),
    ]
