# Generated by Django 2.0.4 on 2018-07-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20180628_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_types',
            field=models.ManyToManyField(related_name='recipe', to='recipes.RecipeType'),
        ),
    ]
