# Generated by Django 2.0.4 on 2018-06-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20180619_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='members',
            new_name='ingredients',
        ),
    ]
