# Generated by Django 2.0.4 on 2018-06-20 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20180619_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientphoto',
            name='ingredient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredients', through='recipes.RecipeIngredient', to='recipes.Ingredient'),
        ),
    ]
