# Generated by Django 2.0.4 on 2018-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20180620_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipedifficulty',
            options={'ordering': ['level']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='recipes.RecipeIngredient', to='recipes.Ingredient'),
        ),
    ]
